/** Lumina voice — warm, direct, diaspora caregiver tone */

export const brand = {
  name: "Lumina",
  tagline: "They ask. You approve.",
  sub: "Care for family back home — on your terms.",
};

export const nav = {
  home: "Home",
  autopilot: "Autopilot",
  history: "History",
  profile: "Profile",
};

export const actions = {
  continue: "Continue",
  back: "Back",
  cancel: "Cancel",
  save: "Save",
  done: "Done",
  seeAll: "View all",
  add: "Add",
  remove: "Remove",
  signIn: "Sign in",
  getStarted: "Get started",
  logOut: "Sign out",
};

export const home = {
  greeting: (name: string) => `Welcome back, ${name}`,
  heroSubIdle: brand.sub,
  heroSubPending: brand.tagline,
  balanceLabel: "Available to send",
  balanceUaLabel: "Unified balance",
  sentMonth: "Sent this month",
  payments: "Payments",
  awaiting: "Needs your OK",
  pullEyebrow: "From home",
  pullTitle: "Waiting on you",
  autopilotEyebrow: "On schedule",
  autopilotTitle: "Autopilot",
  addRule: "Set up autopilot",
  paidSuccess: (amount: number, title: string) => `Sent $${amount} · ${title}`,
  paidSuccessSub: "Money is on its way.",
  portalEyebrow: "From home",
  portalTitle: "Share family portal",
};

export const quick = {
  send: "Send now",
  ask: "Ask",
  rule: "New schedule",
  inbox: "Inbox",
};

export const pull = {
  eyebrow: "From home",
  inboxTitle: "Inbox",
  inboxSub: brand.tagline,
  tabs: { pending: "Waiting", paid: "Sent", declined: "Passed" },
  waitingForYou: "Needs your OK",
  decline: "Not now",
  approve: (amount: number) => `Send $${amount}`,
  approveFull: (amount: number) => `Approve & send $${amount}`,
  seeAll: (n: number) => `All requests (${n})`,
  emptyPending: "Nothing waiting. When family asks, it shows up here.",
  emptyPaid: "No approved requests yet.",
  emptyDeclined: "No passed requests yet.",
  detailTitle: "Request",
  billLabel: "Attached bill",
  payout: "Payout",
  arrives: "Lands in ~10 seconds",
  arrivesShort: "~10 seconds",
  fee: "No fee",
  due: (label: string) => `Due ${label}`,
  paying: (relation: string) => `Sending to ${relation}…`,
  successTitle: "Money sent",
  successBody: (amount: number, name: string) => `$${amount.toFixed(2)} is on its way to ${name}`,
  notified: (relation: string) => `${relation} will get a confirmation.`,
  declined: "You passed on this one.",
  notFound: "This request is no longer here.",
  backHome: "Back to home",
  viewHistory: "See in history",
  newCta: "Log request",
  familyPortal: "Family portal",
  sourceFamily: "From family",
  sourceCaregiver: "You logged",
  emptyCtaAsk: "Try family portal",
  emptyCtaLog: "Log a request",
  noBill: "No bill attached",
  statusPending: "Needs your OK",
  statusPaid: "Sent",
  statusDeclined: "Passed",
  emptyCtaInbox: "Open inbox",
  settlementFailed: "Payment didn't confirm. Try again.",
};

export const settlement = {
  failed: "Payment didn't confirm. Try again.",
  pendingTimeout: "Still waiting for on-chain confirmation.",
  confirming: "Confirming on-chain…",
};

export const fees = {
  luminaFee: "Lumina fee",
  free: "FREE",
  wiseCharge: "Wise would charge",
  saveUpTo: (amount: number) => `You save up to $${amount.toFixed(2)} with Lumina`,
  note: "Arrives in ~10 seconds · No hidden markup",
};

export const portal = {
  title: "Family portal",
  sub: "Share this link — family asks, you approve.",
  linkLabel: "Portal link",
  copy: "Copy link",
  copied: "Copied!",
  share: "Share",
  preview: "Preview",
  shareTitle: "Lumina — ask for care",
  shareText: "Use this link to request support from abroad.",
  shareTextMember: (name: string) => `Hi ${name} — use this link to ask for support from abroad.`,
  onboardingHint: "Send this to family back home so they can ask when they need help.",
  pickMember: "Link for",
  anyone: "Anyone",
  memberShare: "Share link",
  resetLink: "Reset link",
  resetConfirm: "Old links stop working. Family will need the new link.",
  resetDone: "New link ready",
  revoked: "Portal link disabled",
  revokedHint: "Reset link to share with family again.",
  signedHint: "Wallet-signed link · your care graph lives on IPFS",
};

export const toast = {
  newRequest: (name: string, amount: number) => `${name} asked · $${amount}`,
  newRequestSub: "Tap to review and approve",
  autopilotQueue: (label: string, amount: number) => `Autopilot ready · $${amount} · ${label}`,
  autopilotQueueSub: "Tap home to settle on-chain",
  view: "View",
  dismiss: "Dismiss",
};

export const ask = {
  title: "Ask",
  brand: "Family home",
  sub: "Ask your sponsor abroad — they approve in one tap.",
  who: "Who are you?",
  whoSub: "Pick your name below.",
  what: "What do you need?",
  whatSub: "Category and amount.",
  details: "Tell them more",
  detailsSub: "A short note helps them decide faster.",
  review: "Ready to send?",
  reviewSub: "This goes straight to their inbox.",
  messagePh: "Why you need this…",
  billPh: "Bill or reference (e.g. Meralco · Acct 4821)",
  dueLabel: "Due by",
  submit: "Send request",
  sending: "Sending…",
  successTitle: "Request sent",
  successBody: (sponsor: string) => `${sponsor} will see this in their inbox.`,
  successHint: "They'll get a notification. Money lands in ~10s after they approve.",
  sponsorView: "Switch to sponsor view",
  deepLinkGreeting: (name: string) => `Hi, ${name}`,
  welcomeTitle: "Need something from abroad?",
  welcomeSub: "Your sponsor approves in one tap — money lands in ~10 seconds.",
  emptyFamily: "Profile not set up yet",
  emptyFamilySub: "Ask your sponsor to add you in Lumina first.",
  trustStrip: "Private link · only your sponsor sees this",
  pickYou: "Tap your name to continue",
  amountHint: "They approve in one tap — money lands in ~10 seconds.",
  steps: ["Who", "What", "Note", "Send"],
};

export const requestLog = {
  title: "Log request",
  brand: "Log request",
  sub: "Family asked by call or chat — add it to your inbox.",
  pickMember: "Who asked?",
  amountHint: (method: string) => `They shared via ${method} — add to your inbox`,
  reviewEyebrow: "Add to inbox",
  who: "Who asked?",
  whoSub: "Pick the family member.",
  what: "What is it for?",
  whatSub: "Category and amount.",
  details: "Details",
  detailsSub: "Message and bill info they shared.",
  review: "Add to inbox",
  reviewSub: "You can approve it from home.",
  submit: "Add to inbox",
  successTitle: "Added",
  successBody: "It's in your inbox — approve when ready.",
  viewInbox: "Open inbox",
  steps: ["Who", "What", "Note", "Confirm"],
};

export const autopilot = {
  title: "Autopilot",
  brand: "Autopilot",
  sub: "Money that leaves on its own — pulsa, bills, school.",
  eyebrow: "Set & forget",
  newTitle: "New autopilot",
  pickMember: "Choose who receives it",
  amountHint: (method: string) => `Auto-send via ${method} · ~10 seconds each time`,
  reviewEyebrow: "Confirm schedule",
  detailTitle: "Schedule",
  emptyTitle: "Nothing on autopilot yet",
  emptySub: "Pick someone, what to send, and when. Lumina handles the rest.",
  emptyCta: "Set first schedule",
  create: "New autopilot",
  nextLabel: "Up next",
  queueLabel: "Autopilot ready",
  queueSub: (amount: number) => `Tap to settle $${amount.toFixed(0)} on-chain`,
  queueSuccess: (label: string) => `Autopilot sent · ${label}`,
  runNow: "Send now",
  delete: "Remove schedule",
  activate: "Turn on autopilot",
  history: "Past sends",
  activeCount: "On",
  totalCount: "Total",
  paused: "Paused",
  ariaPause: "Pause schedule",
  ariaActivate: "Turn on schedule",
  filters: { all: "All", active: "On", paused: "Paused" },
  detail: {
    schedule: "Schedule",
    nextRun: "Next send",
    payout: "Payout",
    fee: "Fee",
    lastRun: "Last sent",
    amount: "Amount",
    yearly: "Est. yearly",
    sending: "Sending…",
    sentTitle: "Sent!",
    sentBody: (relation: string) => `${relation} will get a confirmation.`,
    sentAmount: (amount: number, label: string) => `$${amount.toFixed(2)} → ${label}`,
    viewHistory: "See in history",
    backHome: "Back to home",
    completed: "Completed",
  },
  schedule: {
    weekly: "Every week",
    weeklySub: "Same day each week",
    monthly: "Every month",
    monthlySub: "Fixed date each month",
    beforeDue: "Before due date",
    beforeDueSub: "Pay bills early automatically",
    daysBefore: (d: number) => `${d} days before`,
    whenTitle: "How often?",
  },
  wizard: {
    who: "Who receives it?",
    whoSub: "Someone in your family list.",
    what: "What are you covering?",
    whatSub: "Pick a category and amount.",
    when: "How often?",
    whenSub: "Lumina sends automatically.",
    review: "Looks good?",
    reviewSub: "Confirm before it goes live.",
    doneTitle: "Autopilot is on",
    doneBody: (relation: string) => `Scheduled sends for ${relation} are live.`,
    firstRun: "First send",
    viewRules: "View schedules",
    steps: ["Who", "What", "When", "Confirm"],
  },
};

export const send = {
  title: "Send now",
  brand: "Send now",
  sub: "One payment — not on a schedule.",
  who: "Who gets it?",
  whoSub: "Tap someone below.",
  pickMember: "Choose who receives it",
  what: "What's it for?",
  amountLabel: "You're sending",
  amountHint: (method: string) => `Via ${method} · lands in ~10 seconds`,
  amount: "Amount",
  payout: "Payout",
  fee: "Fee",
  searchPh: "Search family",
  arrives: (method: string) => `Via ${method} · ~10 sec`,
  review: "Ready to send",
  reviewEyebrow: "Confirm send",
  pay: (amount: number) => `Send $${amount.toFixed(2)}`,
  sending: (relation: string) => `Sending to ${relation}…`,
  successTitle: "Done",
  successBody: (amount: number, name: string) => `$${amount.toFixed(2)} → ${name}`,
  notified: (relation: string) => `${relation} will get a confirmation.`,
  viewHistory: "See in history",
  viewUniversalX: "View on UniversalX",
  backHome: "Back to home",
  steps: ["Who", "Amount", "Confirm", "Done"],
};

export const history = {
  title: "History",
  sub: "Every send — autopilot and approved requests.",
  eyebrow: "Your sends",
  sentMonth: "This month",
  pulls: "You approved",
  onChain: "On-chain",
  empty: "No sends yet.",
  emptySub: "Approve a request or turn on autopilot.",
  emptyCtaPay: "Send now",
  emptyCtaInbox: "Check inbox",
  groups: { today: "Today", yesterday: "Yesterday", earlier: "Earlier" },
};

export const profile = {
  title: "Profile",
  eyebrow: "Account",
  family: "Family",
  familySub: (n: number) => `${n} ${n === 1 ? "person" : "people"}`,
  schedules: "Autopilot schedules",
  notifications: "Notifications",
  security: "Security",
  help: "Help",
  careGroup: "Care",
  prefsGroup: "Preferences",
  supportGroup: "Support",
  dev: "For judges",
  footer: `${brand.name} · ${brand.tagline}`,
};

export const dev = {
  mode: "Mode",
  modeUa: "Universal Account · live",
  modeDemo: "Demo (add Particle env)",
  owner: "Owner (EOA)",
  smartAccount: "Smart account",
  eip7702: "EIP-7702",
  delegated: "Delegated",
  notDelegated: "Not delegated",
  balance: "Unified balance",
  settlement: "Settlement",
  settlementUa: "Cross-chain USDT → Arbitrum",
  settlementDemo: "Simulated ref",
  chain: "Primary chain",
  connect: "Connect wallet",
  disconnected: "Not connected",
  credentials: "Particle credentials",
  configured: "Configured",
  missing: "Missing",
};

export const notifications = {
  title: "Notifications",
  brand: "Alerts",
  sub: "Choose what reaches you.",
  panelEyebrow: "Push notifications",
  requests: "Family requests",
  requestsSub: "When someone asks from home",
  autopilot: "Autopilot sends",
  autopilotSub: "Confirmation after each scheduled send",
  promos: "Tips & updates",
  promosSub: "Occasional product news",
  saved: "Preferences saved",
};

export const security = {
  title: "Security",
  brand: "Security",
  sub: "How you confirm sends.",
  panelEyebrow: "Confirm sends",
  metaEyebrow: "Account",
  biometric: "Face ID",
  biometricSub: "Required to approve and send",
  pin: "Payment PIN",
  pinValue: "Not set",
  sessions: "Active sessions",
  sessionsValue: "This device",
  saved: "Security updated",
};

export const help = {
  title: "Help",
  brand: "Help",
  sub: "Quick answers.",
  faqEyebrow: "Common questions",
  items: [
    {
      q: "How does family ask for money?",
      a: "Share the family portal. They pick their name, enter the amount, and you approve from your inbox.",
    },
    {
      q: "What is Autopilot?",
      a: "Recurring sends — weekly pulsa, monthly school fees, or bills paid days before they're due.",
    },
    {
      q: "Are there fees?",
      a: "Lumina charges no fee. Money lands in ~10 seconds via local wallets like GCash or M-Pesa.",
    },
    {
      q: "Can I log a request manually?",
      a: "Yes — open Inbox and tap Log request when family asked by phone or chat.",
    },
    {
      q: "What is Universal Account?",
      a: "One balance across chains. When you approve, Lumina sources USDT from any chain and settles on Arbitrum — powered by Particle EIP-7702.",
    },
  ],
  contact: "Still need help?",
  contactSub: "We typically reply within one business day.",
  contactCta: "Email support",
};

export const family = {
  title: "Family",
  brand: "Family",
  sub: (n: number) => `Who you send care to · ${n} total`,
  listEyebrow: "Your people",
  add: "Add someone",
  addForm: "New person",
  namePh: "Full name",
  relationPh: "How you're related",
  cancel: "Cancel",
  save: "Add to family",
  saved: "Added to family",
  portalHint: "Share their personal link so they can ask from home.",
};

export const onboarding = {
  brand: "Set up",
  steps: ["Start", "Family", "Done"],
  stepsUa: ["Start", "Wallet", "Family", "Done"],
  welcomeTitle: "Who are you sending for?",
  welcomeSub: "Lumina covers family back home — when they ask, or on a schedule you set.",
  perks: [
    "They request from home — you tap approve",
    "Or set autopilot for pulsa, bills, school",
    "Connect wallet once — autopilot settles on-chain.",
  ],
  perksUa: [
    "One Universal Account across Arbitrum, Base, Ethereum",
    "Cross-chain USDT when you approve a request",
    "EIP-7702 smart account — no seed phrase",
  ],
  walletTitle: "Connect your account",
  walletSub: "Liquidity from any chain settles on Arbitrum when you send.",
  walletConnect: "Connect with Particle",
  walletSkip: "Continue in demo mode",
  walletConnected: (addr: string) => `Connected · ${addr}`,
  walletBalance: (usd: number) => `$${usd.toFixed(2)} unified balance`,
  walletEip7702: "EIP-7702 · Universal Account",
  walletWaiting: "Waiting for wallet…",
  ctaWallet: "Continue",
  familySub: "Your family",
  familyPick: "Choose everyone you'll support",
  addTitle: "Someone else?",
  readyTitle: "You're ready",
  readySub: (n: number) => `Supporting ${n} ${n === 1 ? "person" : "people"} back home.`,
  nextTitle: "What to do first",
  nextItems: [
    "Check inbox for family requests",
    "Set your first autopilot schedule",
    "Send a one-off payment anytime",
  ],
  ctaStart: "Let's go",
  ctaFamily: (n: number) => `Next · ${n} selected`,
  ctaDone: "Open home",
};

export const auth = {
  signIn: "Create account",
  badge: "Secure",
  signInSub: "Continue with Google or Apple — same as any app you trust.",
  signInSubWeb3: "Sign in with your wallet — no email, no password.",
  googleCta: "Continue with Google",
  appleCta: "Continue with Apple",
  emailCta: "Continue with email",
  orDivider: "or",
  walletSecondary: "Use an existing crypto wallet",
  web2Footnote: "We create a secure wallet behind the scenes — no seed phrase to remember.",
  otpTitle: "Check your inbox",
  otpSub: (email: string) => `We sent a code to ${email}`,
  otpHint: "Enter the 6-digit code we sent",
  google: "Google",
  apple: "Apple",
  emailOr: "or use email",
  emailPh: "you@email.com",
  walletCta: "Connect wallet",
  walletHint: "One account across Arbitrum, Base, Ethereum — no seed phrase.",
  walletHintWeb3: "Universal Account or any Web3 wallet. You sign a message — we never see your keys.",
  terms: "By continuing you accept our Terms and Privacy Policy.",
  termsWeb3: "On-chain care hub. Identity = your wallet. Payments settle on Arbitrum.",
  hasAccount: "Already signed in before?",
  walletBootTitle: "Preparing wallet sign-in",
  walletBootSub: "Loading secure connection — one moment.",
  walletBootRetry: "Retry",
  walletBootHint: "Taking longer than usual? Check your connection and tap Retry.",
  walletBootDevHint: "Dev: enter any 0x address below, or run npm run preview:mobile on your Mac.",
};

export const welcome = {
  trust: "Sign in with Google or Apple · wallet secured for you",
  features: [
    "School fees & bills — requested from home",
    "Autopilot for pulsa and recurring care",
    "They know the moment it's paid",
  ],
  cta: "Create account",
  signIn: "I already have an account",
};

export const graph = {
  title: "Care graph",
  eyebrow: "Wallet-owned",
  storageIpfs: "IPFS",
  storageJson: "Local dev",
  storagePostgres: "Hosted",
  cidLabel: "Content ID",
  viewIpfs: "View on IPFS",
  sub: "Family, inbox, and schedules — pinned to your wallet, not our database.",
  compactSub: "Backed by your wallet-owned graph on IPFS.",
  localSub: "Using local dev storage — set PINATA_JWT for IPFS in production.",
  pending: "Syncing to IPFS…",
  copyCid: "Copy CID",
  copied: "Copied!",
  dashboardBadge: "Wallet-owned",
};

export const receipt = {
  title: "Receipt",
  sent: "Sent",
  to: "To",
  for: "For",
  type: "Type",
  status: "Status",
  completed: "Completed",
  fee: "Fee",
  free: "No fee",
  graphProof: "Care graph",
  proof: "Settlement",
  proofSub: "Confirmed on-chain. Family sees it in ~10s.",
  proofUa: "Cross-chain settlement via Universal Account.",
  proofDemo: "Demo mode — simulated reference.",
  viewUniversalX: "View on UniversalX",
  onChain: "On-chain",
  close: "Close",
  types: { auto: "Autopilot", manual: "One-time", pull: "Approved request" },
};

export const bio = {
  approve: { title: "Approve this send", success: "Approved" },
  activate: { title: "Turn on autopilot", success: "Active" },
  pay: { title: "Confirm send", success: "Sent" },
  default: { title: "Confirm with Face ID", success: "Confirmed" },
  tap: "Tap to confirm",
  scanning: "Hold still…",
  uaHint: "Cross-chain USDT via Universal Account",
  demoHint: "Demo settlement — no wallet required",
};

export const meta = {
  title: `${brand.name} — ${brand.tagline}`,
  description: "Family requests and autopilot care for loved ones abroad. Pulsa, bills, school — one tap.",
};